#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 20 08:17:16 2023

@author: gabrielaortiz
"""
import funtions as fn
from data import df

df.loc[:,'mean_1'] = fn.remove_mean(df.iloc[:,0])
df.loc[:,'add_value'] = fn.add_number(df.iloc[:,0],3)

print(df)